// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package providers

import (
	"idnatiya/go-auth/controllers"
	"idnatiya/go-auth/repositories"
	"idnatiya/go-auth/services"
)

// Injectors from injector.go:

func InitializePermission() *controllers.PermissionController {
	permissionRepository := repositories.NewPermissionRepository()
	permissionService := services.NewPermissionService(permissionRepository)
	permissionController := controllers.NewPermissionController(permissionService)
	return permissionController
}

func InitializeFilesystem() *controllers.FileController {
	fileRepository := repositories.NewFileRepository()
	fileService := services.NewFileService(fileRepository)
	fileController := controllers.NewFileController(fileService)
	return fileController
}
