// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package providers

import (
	"idnatiya/go-auth/controllers"
	"idnatiya/go-auth/repositories"
	"idnatiya/go-auth/services"
)

// Injectors from permission.go:

func InitializePermission() *controllers.PermissionController {
	permissionRepository := repositories.NewPermissionRepository()
	permissionService := services.NewPermissionService(permissionRepository)
	permissionController := controllers.NewPermissionController(permissionService)
	return permissionController
}
